server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - name: CircuitBreaker
              args:
                name: account-service-cb
                fallbackuri: forward:/fallback/accounts
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**
          filters:
            - name: CircuitBreaker
              args:
                name: loan-service-cb
                fallbackuri: forward:/fallback/loans

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
